### PR TITLE
Fix to Bellona's passive (Master of war)

### PR DESCRIPTION
**Pull request by RodrigueLemaire**
It just wasn't coded so I added it, I didn't quite test it though.

### CODE REVIEW

**Comment by RodrigueLemaire** [comment]
**Oh my bad I forgot the speed part of the passive, I'll fix that!**

**Comment by RodrigueLemaire** [comment]
- [x] Done!

**Review by sharknice — APPROVED** [review]

**Comment by sharknice** [comment]
Cool, all the updates are on the site now.

**Comment by RodrigueLemaire** [comment]
Nice!

**Pull request merged**
